# Generated by Django 4.0.4 on 2022-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coinslot_options_alter_coinslot_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
