# Generated by Django 4.0.4 on 2022-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_clients_whitelisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='Download_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet download bandwidth in Kbps. No value = unlimited bandwidth'),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='Upload_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet upload bandwidth in Kbps. No value = unlimited bandwidth'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Download_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet download bandwidth in Kbps. No value = unlimited bandwidth'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Upload_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet upload bandwidth in Kbps. No value = unlimited bandwidth'),
        ),
    ]
