# Generated by Django 4.0.4 on 2022-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_whitelist_download_rate_whitelist_upload_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotifications',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='Enabled',
            field=models.BooleanField(default=False, verbose_name='Enable'),
        ),
    ]
