# Generated by Django 4.0.4 on 2022-09-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pushnotifications_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='IP_Address',
            field=models.CharField(max_length=15, unique=True, verbose_name='IP'),
        ),
    ]
