# Generated by Django 4.0.4 on 2022-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_clients_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='IP_Address',
            field=models.CharField(max_length=15, verbose_name='IP'),
        ),
    ]
