# Generated by Django 4.0.4 on 2025-03-07 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_clients_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='lan_port',
            field=models.CharField(blank=True, help_text='Local Network ethernet port. The port used by the wifi access point.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='wan_port',
            field=models.CharField(blank=True, help_text='Internet facing ethernet port.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Minutes',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Internet access duration in hh:mm:ss format. This value can be overridden if rate type is Minutes/Peso in settings', verbose_name='Duration (Custom)'),
        ),
    ]
