# Generated by Django 4.0.4 on 2022-11-16 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_userattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinslot',
            name='Slot_Address',
        ),
        migrations.AddField(
            model_name='coinslot',
            name='Credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
