# Generated by Django 4.0.4 on 2022-11-16 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_remove_coinslot_slot_address_coinslot_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Credentials',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
