# Generated by Django 3.2.7 on 2021-09-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_auto_20210912_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinqueue',
            name='Client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.clients'),
            preserve_default=False,
        ),
    ]
