# Generated by Django 3.2.7 on 2021-09-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_alter_coinqueue_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinqueue',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_queue', to='app.clients'),
        ),
    ]
