# Generated by Django 3.2.7 on 2021-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_alter_coinqueue_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='OpenNDS_Gateway',
            field=models.URLField(default='http://10.0.0.1:2050', help_text='Captive portal gateway server url.'),
        ),
    ]
