# Generated by Django 3.2.7 on 2021-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_settings_opennds_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='FAS_Session',
            field=models.CharField(default='clyde ggwapo', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='Date_Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
