# Generated by Django 3.2.7 on 2021-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_auto_20211001_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='FAS_Session',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
