# Generated by Django 3.2.7 on 2021-10-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_alter_clients_fas_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.settings'),
            preserve_default=False,
        ),
    ]
