# Generated by Django 3.2.7 on 2021-10-04 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_alter_coinslot_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Slot_Timeout',
            field=models.PositiveIntegerField(default=15, help_text='Slot timeout in seconds.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
