# Generated by Django 3.2.7 on 2021-10-09 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_alter_settings_slot_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Connected_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Slot_Timeout',
            field=models.PositiveIntegerField(default=15, help_text='Slot timeout in seconds. Default is 15', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
