# Generated by Django 3.2.7 on 2021-10-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_auto_20211010_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinqueue',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_slot', to='app.clients'),
        ),
    ]
