# Generated by Django 3.2.7 on 2021-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20211014_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
