# Generated by Django 3.2.7 on 2021-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_alter_coinslot_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='queue_coins',
            field=models.IntegerField(default=0),
        ),
    ]
