# Generated by Django 3.2.7 on 2021-10-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_rename_queue_coins_clients_queue_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Queue_Coins',
        ),
    ]
