# Generated by Django 3.2.7 on 2021-10-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_remove_clients_queue_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinqueue',
            name='id',
        ),
        migrations.AlterField(
            model_name='coinqueue',
            name='Client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coin_queue', serialize=False, to='app.clients'),
        ),
    ]
