# Generated by Django 3.2.7 on 2021-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20211017_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_client',
            field=models.ForeignKey(blank=True, help_text='Voucher code user. * Optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_code', to='app.clients', verbose_name='Client'),
        ),
    ]
