# Generated by Django 3.2.7 on 2021-11-06 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_alter_vouchers_voucher_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_time_value',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Time Value'),
        ),
    ]
