# Generated by Django 3.2.7 on 2021-11-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_alter_vouchers_voucher_time_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Show_User_Details',
            field=models.BooleanField(default=False),
        ),
    ]
