# Generated by Django 3.2.7 on 2021-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_settings_show_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Show_User_Details',
            field=models.BooleanField(default=False, help_text='Shows client IP and MAC address on the main portal'),
        ),
    ]
