# Generated by Django 3.2.7 on 2021-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_alter_settings_show_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Pause_Resume_Flg',
            field=models.BooleanField(default=True, help_text='Enables pause/resume function.', verbose_name='Pause/Resume'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Vouchers_Flg',
            field=models.BooleanField(default=True, help_text='Enables voucher module.', verbose_name='Vouchers'),
        ),
    ]
