# Generated by Django 3.2.7 on 2021-11-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_auto_20211106_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Pause_Limit',
            field=models.IntegerField(blank=True, help_text='Sets allowable number of pauses a client can have. No value means unlimited time pauses.', null=True),
        ),
    ]
