# Generated by Django 3.2.7 on 2021-11-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_settings_pause_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='Pause_Limit',
        ),
    ]
