# Generated by Django 3.2.7 on 2021-11-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_remove_settings_pause_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinslot',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Built In'), (1, 'Sub Vendo')], default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
    ]
