# Generated by Django 3.2.7 on 2021-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_auto_20211107_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Built In'), (1, 'Sub Vendo')], default=1),
        ),
    ]
