# Generated by Django 3.2.7 on 2021-11-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_coinslot_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='BG_Image',
        ),
    ]
