# Generated by Django 3.2.7 on 2021-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_remove_settings_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Download_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet download bandwidth in Kbps. No value = unlimited bandwidth', verbose_name='Download Bandwidth'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Upload_Rate',
            field=models.IntegerField(default=0, help_text='Specify client internet upload bandwidth in Kbps. No value = unlimited bandwidth', verbose_name='Upload Bandwidth'),
        ),
    ]
