# Generated by Django 3.2.7 on 2021-11-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_auto_20211120_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='Download_Rate',
            field=models.IntegerField(default=0, help_text='Specify global internet download bandwidth in Kbps. 0 = unlimited bandwidth', verbose_name='Download Bandwidth'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Upload_Rate',
            field=models.IntegerField(default=0, help_text='Specify global internet upload bandwidth in Kbps. 0 = unlimited bandwidth', verbose_name='Upload Bandwidth'),
        ),
    ]
