# Generated by Django 4.0.4 on 2022-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_auto_20211120_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Networking'},
        ),
        migrations.AddField(
            model_name='settings',
            name='Insert_Coin_Sound',
            field=models.BooleanField(default=True, help_text='Enable/disable sound during insert coin.'),
        ),
    ]
