# Generated by Django 4.0.4 on 2022-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_alter_network_options_settings_insert_coin_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_code',
            field=models.CharField(default='TEST', max_length=20, unique=True),
        ),
    ]
