# Generated by Django 4.0.4 on 2022-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_alter_vouchers_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
