# Generated by Django 4.0.4 on 2022-05-19 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_alter_vouchers_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_time_value',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Voucher time duration in hh:mm:ss format.', verbose_name='Time Value'),
        ),
    ]
