# Generated by Django 4.0.4 on 2022-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_alter_vouchers_voucher_time_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_trigger_time',
            field=models.DurationField(blank=True, default='00:00:00', help_text='Notification will fire when time is equal to the specified trigger time. Format: hh:mm:ss', null=True, verbose_name='Notification Trigger'),
        ),
    ]
