# Generated by Django 4.0.4 on 2022-05-20 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_alter_pushnotifications_notification_trigger_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotifications',
            name='notification_trigger_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Notification will fire when time is equal to the specified trigger time. Format: hh:mm:ss', null=True, verbose_name='Notification Trigger'),
        ),
    ]
