# Generated by Django 4.0.4 on 2022-05-20 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_alter_pushnotifications_notification_trigger_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Base_Value',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Base time value for each peso. Specify in hh:mm:ss format. Applicable only if Rate Type is Minutes/Peso', verbose_name='Minutes / Peso'),
        ),
    ]
