# Generated by Django 4.0.4 on 2022-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0143_alter_settings_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='Limit_Allowed_Clients',
            field=models.BooleanField(default=False, help_text='Check if bandwith limiting should be applied to Allowed/Whitelisted devices.'),
        ),
    ]
