# Generated by Django 4.0.4 on 2022-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_network_limit_allowed_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='Download_Rate',
            field=models.IntegerField(default=0, help_text='Specify global internet download bandwidth in Kbps. 0 = unlimited bandwidth', verbose_name='Download Limit'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Upload_Rate',
            field=models.IntegerField(default=0, help_text='Specify global internet upload bandwidth in Kbps. 0 = unlimited bandwidth', verbose_name='Upload Limit'),
        ),
    ]
