# Generated by Django 4.0.4 on 2022-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_alter_network_download_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinslot',
            name='Slot_ID',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='Limit_Allowed_Clients',
            field=models.BooleanField(default=False, help_text='Check if bandwith limiting should also be applied to Allowed/Whitelisted devices.'),
        ),
    ]
