# Generated by Django 4.0.4 on 2022-05-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_alter_coinslot_slot_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinslot',
            name='Counter',
        ),
    ]
