# Generated by Django 4.0.4 on 2022-05-22 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_remove_coinslot_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='Redir_Url',
        ),
        migrations.AlterField(
            model_name='rates',
            name='Minutes',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Internet access duration in hh:mm:ss format', verbose_name='Duration (Custom)'),
        ),
    ]
